version: 2.1
jobs:
  test_kernel:
    docker:
      - image: cimg/base:stable
    resource_class: large
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            sudo apt-get update
            sudo apt-get install -y bc bison build-essential flex git libssl-dev libelf-dev clang lld llvm gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi cpio
            git clone --depth=1 https://github.com/LineageOS/android_kernel_xiaomi_msm8937.git -b lineage-23.2 kernel
      - run:
          name: Build
          command: |
            cd kernel
            export ARCH=arm64
            export SUBARCH=arm64
            export KBUILD_BUILD_USER="Wildan"
            export KBUILD_BUILD_HOST="Kaioxen-Lab"
            mkdir -p out
            
            # Step 1: Generate Config
            make O=out ARCH=arm64 vendor/msm8937_defconfig
            scripts/kconfig/merge_config.sh -O out out/.config arch/arm64/configs/vendor/xiaomi/msm8937/mi8937_exclude_mi8917.config
            
            # Step 2: Fix Build Errors (Disable Broken Features)
            scripts/config --file out/.config --disable CONFIG_IKHEADERS
            scripts/config --file out/.config --disable CONFIG_BPF_PRELOAD
            
            # Step 3: Masak Sampai Jadi Image
            make -j$(nproc --all) O=out \
                ARCH=arm64 \
                CC=clang \
                CLANG_TRIPLE=aarch64-linux-gnu- \
                CROSS_COMPILE=aarch64-linux-gnu- \
                CROSS_COMPILE_ARM32=arm-linux-gnueabi-
      - store_artifacts:
          path: kernel/out/arch/arm64/boot/Image.gz-dtb
          destination: kernel-test-wildan
workflows:
  build_test:
    jobs:
      - test_kernel
