version: 2.1
jobs:
  test_kernel:
    docker:
      - image: cimg/base:stable
    resource_class: large
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            sudo apt-get update
            sudo apt-get install -y bc bison build-essential flex git libssl-dev libelf-dev clang lld llvm gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi
            git clone --depth=1 https://github.com/Mi-Thorium/kernel_msm-4.19.git -b mithorium/a13/tmp/4.19.307 kernel
      - run:
          name: Build
          command: |
            cd kernel
            export ARCH=arm64
            export SUBARCH=arm64
            export KBUILD_BUILD_USER="Wildan"
            export KBUILD_BUILD_HOST="Kaioxen-Lab"
            
            # Fix error drivers/staging/prima/Kconfig
            sed -i '/prima\/Kconfig/d' drivers/staging/Kconfig
            
            mkdir -p out
            # Step 1: Ambil base msm8937_defconfig
            make O=out ARCH=arm64 msm8937_defconfig
            
            # Step 2: Merge fragment config yang lu mau
            scripts/kconfig/merge_config.sh -O out out/.config arch/arm64/configs/vendor/xiaomi/msm8937/mi8937_exclude_mi8917.config
            
            # Step 3: Masak!
            make -j$(nproc --all) O=out \
                ARCH=arm64 \
                CC=clang \
                CLANG_TRIPLE=aarch64-linux-gnu- \
                CROSS_COMPILE=aarch64-linux-gnu- \
                CROSS_COMPILE_ARM32=arm-linux-gnueabi-
      - store_artifacts:
          path: kernel/out/arch/arm64/boot/Image.gz-dtb
          destination: kernel-test-wildan
workflows:
  build_test:
    jobs:
      - test_kernel
